### PR TITLE
RF-14023 + showcase

### PR DESCRIPTION
**Pull request by petrandreev**
If you have a better idea to store and retrieve the original contextmenu event in order to show the contextMenu popup at the proper position, just tell me.

### CODE REVIEW

**Comment by petrandreev** [comment]
Looks weird,  `cause there is no such artifact in the sonatype repo: https://oss.sonatype.org/#nexus-search;quick~wildfly-dist

**Comment by michpetrov** [comment]
@petrandreev, looks like a glitch, the artifact is in the JBoss repo.

**Comment by petrandreev** [comment]
Exactly! That is how i was trying to implement it first, but... if you go with 
*contextMenu.advanced().show()* and then with
*contextMenu.advanced().selectItem()*
the things get messy because it first popups the RF contextMenu and immediately after that
the native browser`context menu positioned somewhere and naturally focused!
I do not want to change the API, but it looks like [selectItem(ChoicePicker picker)](https://github.com/richfaces/richfaces/blob/master/build/page-fragments/src/main/java/org/richfaces/fragment/contextMenu/AbstractPopupMenu.java#L80)
does two things at once: triggers a menu and selects an item. One could think of adding a **boolean** parameter like *showPopup* or providing more methods, i know it affects the existing ITs, but if one is going to test menus with menu groups- there is no way around it but to separate concerns:
1. show popup
2. navigate/select group
3. click item and so on
My main problem in the test case is to make the test execution fail if the menus is not re-rendered properly and do not allow any further clicks/actions. Can we find here the happy medium(;)?

**Comment by ppitonak** [comment]
@petrandreev please create a new issue for context menu page fragment (https://issues.jboss.org/browse/RF) and we can work on it independently of this pull request.

**Comment by petrandreev** [comment]
@ppitonak done: https://issues.jboss.org/browse/RF-14031. What happens now with this PR? should i pull it back and send two separate PRs for JavaScript and later for test cases?

**Comment by michpetrov** [comment]
@petrandreev, if you rebase and force push just the JavaScript changes into your branch it will update this PR correctly, you can then put the rest into a new one. (Currently the first commit is for 14022, so that certainly doesn't belong.)

**Comment by petrandreev** [comment]
I will send two clean PR- one for JS and one for ITs/Showcase later on.

**Pull request closed without merging**
